# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_z7_io.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_rx_0_0/design_1_uart_rx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_rx_0_0 || ORIG_REF_NAME==design_1_uart_rx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart2sample_0_0/design_1_uart2sample_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart2sample_0_0 || ORIG_REF_NAME==design_1_uart2sample_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_bit_changer_seq_0_0/design_1_bit_changer_seq_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_bit_changer_seq_0_0 || ORIG_REF_NAME==design_1_bit_changer_seq_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_fifo_generator_0_0/design_1_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fifo_generator_0_0 || ORIG_REF_NAME==design_1_fifo_generator_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sample_switch_0_0/design_1_sample_switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sample_switch_0_0 || ORIG_REF_NAME==design_1_sample_switch_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2s_0_0/design_1_i2s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_i2s_0_0 || ORIG_REF_NAME==design_1_i2s_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sample2uart_0_0/design_1_sample2uart_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sample2uart_0_0 || ORIG_REF_NAME==design_1_sample2uart_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_uart_tx_0_0/design_1_uart_tx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_uart_tx_0_0 || ORIG_REF_NAME==design_1_uart_tx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_2_0/design_1_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_2_0 || ORIG_REF_NAME==design_1_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_flip_flop_0_0/design_1_flip_flop_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_flip_flop_0_0 || ORIG_REF_NAME==design_1_flip_flop_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_3_1/design_1_xlconstant_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_3_1 || ORIG_REF_NAME==design_1_xlconstant_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_flip_flop_1_0/design_1_flip_flop_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_flip_flop_1_0 || ORIG_REF_NAME==design_1_flip_flop_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_4_1/design_1_xlconstant_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_4_1 || ORIG_REF_NAME==design_1_xlconstant_4_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tristate_buffer_0_0/design_1_tristate_buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tristate_buffer_0_0 || ORIG_REF_NAME==design_1_tristate_buffer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tristate_buffer_1_0/design_1_tristate_buffer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tristate_buffer_1_0 || ORIG_REF_NAME==design_1_tristate_buffer_1_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
